#!/bin/bash

CPU=1
SECAL='100000'
SECAL_YN='yes'
SRCLUST_CMD='srClust2'
ICAT='cat'

help_text() {
    echo "usage: $1 -1 FASTX_LEFT_PAIRED_END_READS -2 FASTX_RIGHT_PAIRED_END_READS -o OUTPUT_DIR [-p THREADS] [-u|--uniqify] [-g FASTX_GUIDING_CONTIGS] [-b FASTX_BASE_ASSEMBLY] [-t TEMPARORY_DIRECTORY] [-c CLUSTER_FILE] [--secondary-alignments N_SECONDARY_ALIGNMENTS] [--old-style-sr-clustering]"
    echo "       $1 -h  #to show this help"
    echo "       $1 -d  #to check dependencies and quit"
}

force_fasta() {
    if type seqtk &> /dev/null; then
	seqtk seq -AC ${@}
    else
	awk '(/^[@>]/){sub(/^@/,">"); print $1; next}(/^+/){getline;next}{print}' ${@}
    fi
}

THIS_CMD=${0}

cd `dirname ${BASH_SOURCE[0]}`

while (( "$#" )); do
    if [ ${1:0:1} == '-' ]; then
	if [ ${1:1:2} == '1' ]; then
	    INPUT_FASTX_1=${2}
	elif [ ${1:1:2} == '2' ]; then
	    INPUT_FASTX_2=${2}
	elif [ ${1:1:2} == 'g' ]; then
	    GUIDING_CONTIGS=${2}
	elif [ ${1:1:2} == 'b' ]; then
	    BASE_ASSEMBLY=${2}
	elif [ ${1:1:2} == 'c' ]; then
	    CLUSTER_FILE=${2}
	elif [ ${1:1:2} == 'o' ]; then
	    OUTPUT_DIR=${2}
	elif [ ${1:1:2} == 't' ]; then
	    TMP_DIR=${2}
	elif [ ${1:1:2} == 'p' ]; then
	    CPU=${2}
	elif [ ${1:1:2} == 'u' ]; then
	    UNIQ=t
	elif [ ${1:1:2} == 'd' ]; then
	    DEP_CHECK=t
	elif [ ${1:1:2} == 'h' ]; then
	    help_text "${THIS_CMD}"
	    exit 0
	elif [ ${1:1:1} == '-' ]; then
	    if [ ${1:2:6} == 'second' ]; then
		SECAL=${2}
		[ ${SECAL} == '0' ] && SECAL_YN='no'
	    elif [ ${1:2:9} == 'old-style' ]; then
		OLD_STYLE=t
		SRCLUST_CMD='srClust'
	    elif [ ${1:2:3} == 'u' ]; then
		UNIQ=t
	    fi
	fi
    fi
    shift
done

[ -z ${BASE_ASSEMBLY+x} ] && DO_BASE=transabyss
[ -z ${CLUSTER_FILE} ] && DO_CLUST=isONclust

if [ -z ${INPUT_FASTX_1+x} ] || [ -z ${INPUT_FASTX_2+x} ] || [ -z ${OUTPUT_DIR+x} ]; then
    help_text "${THIS_CMD}"
    MUST_EXIT=t
elif ! [ -z ${INPUT_FASTX_1+x} ] && [ -z ${INPUT_FASTX_1: -3} == '.gz' ]; then
    DO_ZCAT='zcat'
    ICAT='zcat'
elif ! [ -z ${GUIDING_CONTIGS+x} ] && [ -z ${GUIDING_CONTIGS: -3} == '.gz' ]; then
    DO_ZCAT='zcat'
fi

# The helping-command srClust(2)? needs to exist in the same
# directory as clustrast, OR be available through $PATH.
if [ -x ${SRCLUST_CMD} ]; then
    SRCLUST_CMD="./${SRCLUST_CMD}"
else
    DO_SRCLUST=${SRCLUST_CMD}
fi

DEPS="awk cut sed sort join ${DO_BASE} minimap2 ${DO_CLUST} ${DO_SRCLUST} ${DO_ZCAT} python3 shannon_cpp"
for command in ${DEPS}; do
    if ! type -P ${command} &> /dev/null; then
	MISSING="${MISSING} ${command}"
    fi
done
if ! [ -z ${MISSING+x} ]; then
    echo "DEPENDECY ERROR: The following dependencies of ClusTrAsT cannot be found in \$PATH:"
    echo "DEPENDECY ERROR:${MISSING}"
    MUST_EXIT=t
fi

if ! [ -z ${DEP_CHECK+x} ]; then
    if [ -z ${MUST_EXIT+x} ]; then
	echo "All dependencies installed!"
    fi
    exit 0
fi

if [ ! -z ${OUTPUT_DIR+x} ] && ! mkdir -p ${OUTPUT_DIR}; then
    echo "ARGUMENT ERROR: Could not create given output directory!"
    MUST_EXIT=t
fi

if [ ! -f ${INPUT_FASTX_1} ] || [ ! -f ${INPUT_FASTX_2} ]; then
    echo "ARGUMENT ERROR: At least one of the paired-ended input files does not appear to exist!"
    MUST_EXIT=t
fi

if ! [ -z ${MUST_EXIT+x} ];then
    #echo "Will exit ClusTrAsT."
    exit 1
fi

if [ -z ${TMP_DIR+x} ]; then
    TMP_DIR=${OUTPUT_DIR}
fi

mkdir -p ${TMP_DIR}

if [ -z ${BASE_ASSEMBLY+x} ]; then
    # Run TransABySS!
    echo "No base assembly given! Will generate one by TransABySS."
    KMERS="25 32 39 46 53"
    for K in ${KMERS}; do
	transabyss -k ${K} --pe ${INPUT_FASTX_1} ${INPUT_FASTX_2} --cleanup 3 --threads ${CPU} --outdir ${TMP_DIR}/ab/${K} --stage dbg || test -f ${TMP_DIR}/ab/${K}/transabyss.DBG.COMPLETE &
    done
    wait
    for K in ${KMERS}; do
	transabyss -k ${K} --pe ${INPUT_FASTX_1} ${INPUT_FASTX_2} --cleanup 3 --threads ${CPU} --outdir ${TMP_DIR}/ab/${K}
    done
    transabyss-merge --mink 25 --maxk 53 ${TMP_DIR}/ab/*/transabyss-final.fa --threads ${CPU} --abyssmap --out ${TMP_DIR}/base-assembly.fa
    rm -rf ${TMP_DIR}/ab
    BASE_ASSEMBLY=${TMP_DIR}/base-assembly.fa
fi

if [ -z ${CLUSTER_FILE+x} ]; then
    mkdir -p ${TMP_DIR}/tmp
    if [ "${GUIDING_CONTIGS: -3}" == ".gz" ]; then
	GC=${GUIDING_CONTIGS##*/}
	zcat ${GUIDING_CONTIGS} > ${TMP_DIR}/tmp/${GC%.gz}
	GUIDING_CONTIGS=${TMP_DIR}/tmp/${GC%.gz}
    elif [ -z ${GUIDING_CONTIGS+x} ]; then
	echo -n "No guiding contigs given! "
	echo "Will use the base assembly for this purpose."
	GUIDING_CONTIGS=${BASE_ASSEMBLY}
    fi
    # force fastq format
    awk 'BEGIN{c=0}(/^[@>]/ && c!=0){printf "\n+\n%s\n";for(i=0;i<c;++i){printf "H"};printf "\n";c=0}(/^@/){print $1;getline;print $0;getline;print "+";getline;print;next}(/^>/){sub(/^>/,"@"); print $1;c=0;next}{c+=length($0);printf "%s",$0}END{if (c>0){printf "\n+\n";for(i=0;i<c;++i){printf "H"};printf "\n"}}' ${GUIDING_CONTIGS} > ${TMP_DIR}/gc.fq
    # RUN isONclust!
    isONclust --isoseq --t ${CPU} --fastq ${TMP_DIR}/gc.fq --outfolder ${TMP_DIR}/tmp
    mv ${TMP_DIR}/tmp/final_clusters.tsv ${TMP_DIR}/final_clusters.tsv
    rm ${TMP_DIR}/tmp ${TMP_DIR}/gc.fq -rf
    CLUSTER_FILE=${TMP_DIR}/final_clusters.tsv
fi

CLUSTER_DIR=${TMP_DIR}/clusters
if ! [ -z ${OLD_STYLE+x} ]; then
    minimap2 -ax sr --secondary=${SECAL_YN} -N${SECAL} -t ${CPU} ${GUIDING_CONTIGS} ${INPUT_FASTX_1} ${INPUT_FASTX_2} > ${TMP_DIR}/align.sam
    #This is (was) the true bottleneck!
    ${SRCLUST_CMD} --output ${CLUSTER_DIR} ${CLUSTER_FILE} ${TMP_DIR}/align.sam &
else
    set -e
    minimap2 -2 -x sr --secondary=${SECAL_YN} -N${SECAL} --paf-no-hit -t ${CPU} ${GUIDING_CONTIGS} ${INPUT_FASTX_1} ${INPUT_FASTX_2} | \
	awk '{ sub(/\/[12]$/,"",$1); print $1"\t"$6; }' | uniq > ${TMP_DIR}/align.csv
    grep -s '^unmapped' ${TMP_DIR}/final_clusters.tsv || echo -e 'unmapped\t*' >> ${TMP_DIR}/final_clusters.tsv
    sort -k2 --parallel=${CPU} -S40% ${TMP_DIR}/align.csv > ${TMP_DIR}/align.sorted.tsv
    rm ${TMP_DIR}/align.csv
    sort -k2 --parallel=${CPU} -S40% ${TMP_DIR}/final_clusters.tsv > ${TMP_DIR}/final_clusters.sorted.tsv
    rm ${TMP_DIR}/final_clusters.tsv
    join -j 2 ${TMP_DIR}/final_clusters.sorted.tsv ${TMP_DIR}/align.sorted.tsv | cut -d' ' -f2-3 | uniq > ${TMP_DIR}/sr_clusters.tsv
    rm -f ${TMP_DIR}/final_clusters.sorted.tsv ${TMP_DIR}/align.sorted.tsv
    sort -k1n,1 --parallel=${CPU} -S40% ${TMP_DIR}/sr_clusters.tsv | uniq > ${TMP_DIR}/sr_clusters.sorted.tsv
    rm -f ${TMP_DIR}/sr_clusters.tsv
    mv ${TMP_DIR}/sr_clusters.sorted.tsv ${TMP_DIR}/sr_clusters.tsv
    set +e
fi

[ -z ${OLD_STYLE+x} ] && ${SRCLUST_CMD} --output ${CLUSTER_DIR} ${TMP_DIR}/sr_clusters.tsv <(${ICAT} ${INPUT_FASTX_1} | force_fasta -) <(${ICAT} ${INPUT_FASTX_2} | force_fasta -) &
${ICAT} ${INPUT_FASTX_1} | awk 'BEGIN{l=0}(NR%2==0 && l<length($0)){l=length($0)}END{print l}' > ${TMP_DIR}/len1.txt &
RL1PID=${!}
${ICAT} ${INPUT_FASTX_2} | awk 'BEGIN{l=0}(NR%2==0 && l<length($0)){l=length($0)}END{print l}' > ${TMP_DIR}/len2.txt &
RL2PID=${!}
wait ${RL1PID} ${RL2PID}
rm -f ${TMP_DIR}/align.*
export RDLEN_1=`cat ${TMP_DIR}/len1.txt`
export RDLEN_2=`cat ${TMP_DIR}/len2.txt`

open_sem(){
    mkfifo pipe-$$
    exec 3<>pipe-$$
    rm pipe-$$
    local i=$1
    for((;i>0;i--)); do
        printf %s 000 >&3
    done
}

run_with_lock_no_exit(){
    local x
    read -u 3 -n 3 x && ((0==x)) || exit $x
    (
     ( "$@"; )
     RVAL=$?
     if [ $((${RVAL})) -ne 0 ]; then
         printf 'WARNING: Process failed with return value no %.3d: %s\n' ${RVAL} "${1}" >&2
     fi
     printf '%.3d' 0 >&3
    )&
}

shannon_cl(){
    f=${1}
    CPU=${2:-1}
    MEM=${3:-20}

    F_1=${f}/1.fq
    F_2=${f}/2.fq
    [ -z ${OLD_STYLE+x} ] && while test ! -f ${f}/done.txt; do sleep 1; done
    [ -f ${f}/1.fq.gz ] && F_1=${f}/1.fq.gz
    [ -f ${f}/2.fq.gz ] && F_2=${f}/2.fq.gz
    if [ -f ${F_1} ]; then
	echo >&2 "${f} EXISTS! STARTING...."
	shannon_cpp shannon --output_dir ${f}/tmp --pair_read_length ${RDLEN_1} ${RDLEN_2} --PE_read_path ${F_1} ${F_2} --num_process=${CPU} --avail_mem=${MEM}G --bypass_pre_correct_read --num_sort_thread=${CPU} > /dev/null 2>&1
	RES=${?}
	while [ ${RES} -eq 0 ] && test ! -s ${f}/tmp/reconstructed_seq.fasta && [ ${CPU} -le 128 ]; do
	    # hack: in a few occurences, shannon seems to only produce output in parallel mode!
	    CPU=$(( ${CPU} * 2 ))
	    echo >&2 "${f} RETRIES WITH CPU=${CPU}...."
	    shannon_cpp shannon --output_dir ${f}/tmp --pair_read_length ${RDLEN_1} ${RDLEN_2} --PE_read_path ${F_1} ${F_2} --num_process=${CPU} --avail_mem=${MEM}G --bypass_pre_correct_read --num_sort_thread=2 > /dev/null 2>&1
	    RES=${?}
	done
	if [ ${RES} -ne 0 ]; then
	    echo >&2 "${f} FAILED!"
	    rm ${f} -rf
	elif test -s ${f}/tmp/reconstructed_seq.fasta; then
	    echo >&2 "${f} FINISHED! MOVE THE FILES..."
	    if [ -z ${OLD_STYLE+x} ]; then
		ln -sf ${f}/tmp/reconstructed_seq.fasta ${f}/transcripts.fa
	    else
		cp ${f}/tmp/reconstructed_seq.fasta ${f}/transcripts.fa
		rm ${f}/tmp -rf
	    fi
	    rm ${F_1} ${F_2} ${f}/done.txt -fr
	else
	    echo >&2 "${f} NO OUTPUT!"
	    rm ${f} -rf
	fi
    else
	echo >&2 "${f} IS MISSING!"
	rm ${f} -rf
    fi
}

smart_merge() {
    touch ${TMP_DIR}/out.raw.fa
    while test -z "$(find ${CLUSTER_DIR} -maxdepth 0 -empty)"; do
	for f in ${CLUSTER_DIR}/*/transcripts.fa; do
	    DIR=${f%/*}
	    CLUST=${DIR##*/}
	    [ "${CLUST}" == "*" ] && continue
	    test -f ${f}/done.txt && continue
	    sed "/^>/s/^>/>${CLUST}_/g" ${f} >> ${TMP_DIR}/out.raw.fa
	    while ! rm ${DIR} -fr; do sleep 1; done
	done
	sleep 5
    done
}

if ! [ -z ${OLD_STYLE+x} ]; then
    wait
    open_sem ${CPU}
    run_with_lock_no_exit shannon_cl ${CLUSTER_DIR}/unmapped
    for f in ${CLUSTER_DIR}/[0-9]* ; do
	test -s ${f}/transcripts.fa && continue
	run_with_lock_no_exit shannon_cl ${f}
    done
    wait
    smart_merge
else
    CLUSTERS=`cut -f1 -d ' ' ${TMP_DIR}/sr_clusters.tsv | uniq`
    mkdir -p ${CLUSTER_DIR}
    touch ${CLUSTER_DIR}/running.txt
    open_sem $(( ${CPU} - 1 ))
    run_with_lock_no_exit smart_merge
    for i in "${CLUSTERS}"; do
	f=${CLUSTER_DIR}/${i}
	test -s ${f}/transcripts.fa && continue
	run_with_lock_no_exit shannon_cl ${f}
    done
    rm -f ${CLUSTER_DIR}/running.txt
    wait
fi

cp ${TMP_DIR}/out.raw.fa ${TMP_DIR}/out.fa
rm -rf ${CLUSTER_DIR}
sed "/^>/s/^>/>base_/g" ${BASE_ASSEMBLY} >> ${TMP_DIR}/out.fa

if ! [ -z ${UNIQ+x} ]; then
    awk '(/^>/){ printf "%s\t",$1}(!/^>/){ print }' ${TMP_DIR}/out.fa | \
	sort --key=2 --parallel=${CPU} -S40% | uniq --skip-fields=1 | \
	awk '{print $1"\n"$2}' > ${OUTPUT_DIR}/clustrast.out.fa
    awk '(/^>/){ printf "%s\t",$1}(!/^>/){ print }' ${TMP_DIR}/out.raw.fa | \
	sort --key=2 --parallel=${CPU} -S40% | uniq --skip-fields=1 | \
	awk '{print $1"\n"$2}' > ${OUTPUT_DIR}/clustrast.out.raw.fa
else
    mv ${TMP_DIR}/out.fa ${OUTPUT_DIR}/clustrast.out.fa
    mv ${TMP_DIR}/out.raw.fa ${OUTPUT_DIR}/clustrast.out.raw.fa
fi
rm -fr ${TMP_DIR}/out.fa ${TMP_DIR}/out.raw.fa ${TMP_DIR}/tmp

echo "Thank you for running ClusTrAsT! Have a nice day!"
